### ISSUE TITLE
[Bug]: Plugin does not send release MBID to ListenBrainz

### ISSUE THREAD

**Issue by zliebersbach** [lyarenei/jellyfin-plugin-listenbrainz#116]
### Bug description

Listens on ListenBrainz do not match with the correct MBIDs.

Potentially related: #52

### Steps to reproduce

1. Play track where the album has release MBIDs, but the track does not (I have tried refreshing metadata to see in the MB plugin would populate track IDs and it doesn't seem to - [checking the codebase, I don't see a `MusicBrainzTrackProvider` either](https://github.com/jellyfin/jellyfin/tree/master/MediaBrowser.Providers/Plugins/MusicBrainz))

**Album**
<img width="816" alt="Screenshot 2024-12-19 at 13 17 09" src="https://github.com/user-attachments/assets/8ec7c1e3-14b5-4ef2-95c2-2cd0e7eee64e" />

**Track**
<img width="816" alt="Screenshot 2024-12-19 at 13 17 25" src="https://github.com/user-attachments/assets/db4016e7-d196-4ada-8e1d-6b926fa7d4aa" />

2. Observe the plugin does not send release MBIDs from the album
```
[2024-12-19 12:58:51.800 +11:00] [DBG] [3] Jellyfin.Plugin.ListenBrainz: Picking up playback start event for item "リボルバー"
[2024-12-19 12:58:51.801 +11:00] [INF] [3] Jellyfin.Plugin.ListenBrainz: Processing playback start event for item "リボルバー" associated with user "Zoe"
[2024-12-19 12:58:51.803 +11:00] [DBG] [3] Jellyfin.Plugin.ListenBrainz: Checking if item is in any allowed libraries
[2024-12-19 12:58:51.809 +11:00] [DBG] [3] Jellyfin.Plugin.ListenBrainz: Item is in at least one allowed library
[2024-12-19 12:58:51.811 +11:00] [DBG] [3] Jellyfin.Plugin.ListenBrainz: Checking if ListenBrainz submission is enabled for the user
[2024-12-19 12:58:51.811 +11:00] [DBG] [3] Jellyfin.Plugin.ListenBrainz: ListenBrainz submission is enabled for the user
[2024-12-19 12:58:51.812 +11:00] [DBG] [3] Jellyfin.Plugin.ListenBrainz: Checking item basic metadata
[2024-12-19 12:58:51.814 +11:00] [DBG] [3] Jellyfin.Plugin.ListenBrainz: Item has basic metadata
[2024-12-19 12:58:51.814 +11:00] [DBG] [3] Jellyfin.Plugin.ListenBrainz: All checks passed, preparing for sending listen
[2024-12-19 12:58:51.815 +11:00] [DBG] [3] Jellyfin.Plugin.ListenBrainz: Checking if MusicBrainz integration is enabled
[2024-12-19 12:58:51.815 +11:00] [DBG] [3] Jellyfin.Plugin.ListenBrainz: MusicBrainz integration is enabled
[2024-12-19 12:58:51.815 +11:00] [INF] [3] Jellyfin.Plugin.ListenBrainz: Getting additional metadata...
[2024-12-19 12:58:51.817 +11:00] [INF] [3] Jellyfin.Plugin.ListenBrainz: Additional metadata are not available: "Audio item does not have a track MBID"
[2024-12-19 12:58:51.817 +11:00] [DBG] [3] Jellyfin.Plugin.ListenBrainz: Additional metadata are not available
System.ArgumentException: Audio item does not have a track MBID
   at Jellyfin.Plugin.ListenBrainz.Clients.MusicBrainzClient.GetAudioItemMetadata(BaseItem item)
   at Jellyfin.Plugin.ListenBrainz.PluginImplementation.OnPlaybackStart(Object sender, PlaybackProgressEventArgs args)
[2024-12-19 12:58:52.029 +11:00] [INF] [3] Jellyfin.Plugin.ListenBrainz: Sending 'playing now' listen...
[2024-12-19 12:58:52.150 +11:00] [DBG] [3] Jellyfin.Plugin.ListenBrainz.ListenBrainzApi: Waiting for previous request to complete (if any)
[2024-12-19 12:58:52.150 +11:00] [DBG] [3] Jellyfin.Plugin.ListenBrainz.ListenBrainzApi: Sending request...
[2024-12-19 12:58:52.174 +11:00] [DBG] [3] Jellyfin.Plugin.ListenBrainz.ListenBrainzApi: Sending request:
Method: "POST"
URI: https://api.listenbrainz.org/1/submit-listens
Data: "{\"listen_type\":\"playing_now\",\"payload\":[{\"track_metadata\":{\"artist_name\":\"yonige\",\"track_name\":\"リボルバー\",\"release_name\":\"リボルバー\",\"additional_info\":{\"tracknumber\":1,\"tags\":[],\"media_player\":\"Jellyfin\",\"submission_client\":\"ListenBrainz plugin for Jellyfin\",\"submission_client_version\":\"5.0.2.0\",\"duration_ms\":186000}}}]}"
[2024-12-19 12:58:53.251 +11:00] [DBG] [24] Jellyfin.Plugin.ListenBrainz.ListenBrainzApi: Response status is OK, will not retry
[2024-12-19 12:58:53.254 +11:00] [DBG] [24] Jellyfin.Plugin.ListenBrainz.ListenBrainzApi: Got response:
Status: OK
Data: "{\"status\":\"ok\"}
"
```
4. Observe ListenBrainz matches the listen to the incorrect MBID
```
{
  "inserted_at": 1734572062,
  "listened_at": 1734572061,
  "recording_msid": "5a0599ba-c2ca-4768-af79-4d92b74ecb22",
  "track_metadata": {
    "additional_info": {
      "duration_ms": 186000,
      "media_player": "Jellyfin",
      "recording_msid": "5a0599ba-c2ca-4768-af79-4d92b74ecb22",
      "submission_client": "ListenBrainz plugin for Jellyfin",
      "submission_client_version": "5.0.2.0",
      "tags": [],
      "tracknumber": 1
    },
    "artist_name": "yonige",
    "mbid_mapping": {
      "artist_mbids": [
        "d473a353-c709-408d-b32b-cc4952bdf6d8"
      ],
      "artists": [
        {
          "artist_credit_name": "yonige",
          "artist_mbid": "d473a353-c709-408d-b32b-cc4952bdf6d8",
          "join_phrase": ""
        }
      ],
      "caa_id": 26177270994,
      "caa_release_mbid": "4c2a15fe-d71a-453c-bc81-3993f9bd1fe5",
      "recording_mbid": "df703ae9-430a-4d76-a451-e63208c20386",
      "recording_name": "リボルバー",
      "release_mbid": "4c2a15fe-d71a-453c-bc81-3993f9bd1fe5"
    },
    "release_name": "リボルバー",
    "track_name": "リボルバー"
  },
  "user_name": "redacted"
}
```

### Expected behavior

The plugin should fallback to the release MBID from the album if it isn't set on the track.

**OR**

The MusicBrainz plugin should be adding release and artist MBIDs to the track.

### Plugin version

5.0.2.0

### Jellyfin Version

10.10.3

**Comment by lyarenei** [comment]
Hi @zliebersbach, thanks for the report.

This is correct behavior. In some cases there might be a recording without a release (MusicBrainz calls them [standalone recordings](https://wiki.musicbrainz.org/Standalone_Recording)). I'm not sure how this would be categorized in Jellyfin (probably a dummy album or something) but as these standalone recordings exist, the plugin can't always fall back to JF album metadata and so relies on sourcing the metadata from the track itself only.

I don't know how rare the standalone recordings are, but I guess most of the people will have Jellyfin set up with their own ripped albums, so the fallback could be probably a configurable option.

**Comment by zliebersbach** [comment]
Thanks, @lyarenei 

Just a bit confused, so since the MB plugin for Jellyfin does not populate MBIDs on _**any**_ tracks, we are expected to manually populate MBIDs for all of our tracks in order for the LB plugin to send correct metadata?

Maybe there's room to improve the MB plugin to add correct metadata to tracks? What do you think?

**Comment by zliebersbach** [comment]
Thanks for your comprehensive response!

> manually

Yes, I get I could use Picard, but that's still an extra manual step that I'd like to avoid. The workflow I'm using currently is to place media directly into Jellyfin and let it ID tracks for me. I'll definitely see if they're open to a contribution in the JF plugin to populate the track MBIDs!

**Comment by zliebersbach** [comment]
> the plugin can't always fall back to JF album metadata

Afterthought, could we check if the currently playing item is a standalone recording, and if it's part of an album, attach the album's MBID to the LB API call?

**Comment by lyarenei** [comment]
@zliebersbach Sorry for the late reply, I had to move and all that stuff.

> Could we check if the currently playing item is a standalone recording, and if it's part of an album, attach the album's MBID to the LB API call?

This should be possible. If a recording is standalone, it should not have any releases. However, if it is, then it is quite common that there are multiple recordings. The plugin could just pick up the first one, but this will inevitably lead to submitting incorrect data - which I personally don't like.

**Comment by moisespr123** [comment]
I'd recommend using Picard to tag your files, then let Jellyfin replace the metadata. this has worked very well for me and it makes this plugin send the correct details to ListenBrainz.

Yes, it is a manual process but at the end you'll have your files properly tagged according to the data MusicBrainz has, assuming you matched your files with the correct release (note that release groups may have more than 1 release for your albums).

**Comment by Zentheon** [comment]
I wanted to finally start having proper metadata on my music, so I too got into Picard and quickly realized that, as fantastic of a tool it is, it'll only take you so far depending on how refined you really want to go. MusicBrainz is a great database, but it has its limits, which is exactly why I started contributing to it recently.

My process has been to import batches into Picard by artist, do an AcousticID scan and then Lookup pass if anything was missed. Usually some manual correction is required with Lookup as it isn't very smart I've found. When anything is still missing or inconsistent is usually when making your own edits comes in.
