### ISSUE TITLE
Listen cache fails to initialize

### ISSUE THREAD

**Issue by lyarenei** [lyarenei/jellyfin-plugin-listenbrainz#42]
Plugin name is different when installed from repository:
```
[2023-08-06 00:23:41.490 +02:00] [ERR] [61] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error
System.IO.DirectoryNotFoundException: Could not find a part of the path '/config/plugins/Jellyfin.Plugin.ListenBrainz/cache.json'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.OpenRead(String path)
   at Jellyfin.Plugin.ListenBrainz.Managers.CacheManager.Restore()
   at Jellyfin.Plugin.ListenBrainz.Tasks.ResubmitListensTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
```

**Comment by lyarenei** [comment]
Caused by differing zip file name from the assembly name: https://github.com/jellyfin/jellyfin/issues/10091

**Comment by lyarenei** [comment]
Closing for now.
