### ISSUE TITLE
Malfunctions on Jellyfin 10.8.0-alpha2

### ISSUE THREAD

**Issue by rigrig** [lyarenei/jellyfin-plugin-listenbrainz#5]
In Jellyfin 10.8.0-alpha2, the plugin has "Status: Malfunctioned"

Jellyfin Version: 10.8.0-alpha2
Plugin version: 1.2.0.0
Operating System: Linux (docker on Synology NAS)
Architecture: X64

What looks like the relevant part of my Docker log:
```
[10:43:55] [ERR] Error creating Jellyfin.Plugin.Listenbrainz.ServerEntryPoint
System.TypeLoadException: Could not load type 'MediaBrowser.Model.Serialization.IJsonSerializer' from assembly 'MediaBrowser.Model, Version=10.8.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeConstructorInfo.<get_Signature>g__LazyCreateSignature|19_0()
   at System.Reflection.RuntimeConstructorInfo.GetParameters()
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
```

**Comment by lyarenei** [comment]
Thanks for letting me know. Looks like JF 10.8 brought some new incompatibilities with older versions, but nothing too hard to fix. I'll take a look at it when I get some time, probably at the weekend. 🙂

**Comment by lyarenei** [comment]
The updated plugin can be installed from this repository: https://raw.githubusercontent.com/lyarenei/jellyfin-plugin-listenbrainz/10.8.x-compat/manifest.json

When the stable version comes out, I'll add it to the master repo.
Please leave this issue open for visibility, thanks. 🙂

**Comment by rigrig** [comment]
Thanks! Confirmed it works again. (and thanks for the repo)
